### ISSUE TITLE
Workflows cannot be used with YouTrack versions > 2017.2

### ISSUE THREAD

**Issue by netsrotr** [JetBrains/youtrack-workflows#12]
Because the recent versions use JavaScript as their workflow driver. All workflows should be migrated to be usable with recent YT versions, aka migrate to JavaScript.

**Comment by mariyadavydova** [comment]
This is not true. Of course, the workflows have to be converted, and we'll start converting them pretty soon.
However, the old-style workflows can be used with YT > 2017.2. If you encounter problems when uploading one of these workflows to YT 2017.3, please file a bug (as such an operation is expected to work for at least a half of a year more).

**Comment by netsrotr** [comment]
Yes, I might be able to upload one. But I cannot change it then from within YT 2017.3, right?

**Comment by mariyadavydova** [comment]
@netsrotr You can do it with external Workflow Editor (the same one which was used prior to YT 2017.2). However, if there is one particular workflow you need, you may tell me, I will put it into the priority queue for reimplementing in new API.

**Comment by netsrotr** [comment]
I would be fine with that external editor: but there is no download anymore on your site. Can you provide a link, please?

**Comment by mariyadavydova** [comment]
Oh yes, it is hidden deep in 'Previous releases' page: https://www.jetbrains.com/youtrack/download/previous.html. I would recommend using OVA, as it comes with Java 6 bundled, which is required for the old version of the workflow editor.
