### ISSUE TITLE
Status Management workflow conflicts with other types

### ISSUE THREAD

**Issue by bijington** [JetBrains/youtrack-workflows#23]
I have tried to include the [Status Management](https://github.com/JetBrains/youtrack-workflows/tree/master/js/status-management) inside of an existing project so that I can include tests within the same projects. However I have run in to the issue that when I try to create a new Bug or change the Type. It complains with the following error message:

> The Status field is not supported for issues with Type: Bug

Is it possible to guide me on how to modify this workflow to conditionally work when others types are used?

**Comment by bijington** [comment]
Sorry it was my misunderstanding. It turns out because I was trying to hide the `Status` field for other types like Bug then it caused the issue. If I should this `Status` field then it does behave. It would still be nice to hide this field if it isn't directly related to the type but I can live with this for now

**Comment by lzalog** [comment]
Hi, 
Thanks for your comment. We will consider this improvement to be included in the standard workflow.
