### ISSUE TITLE
YouTrack not GDPR compliant

### ISSUE THREAD

**Issue by flowl** [JetBrains/youtrack-workflows#29]
I cannot delete my own comments in YouTrack.
Instead there is a fake-delete button that allows me to "hide" my own comment.

The administrator cannot give permission to allow someone to delete its own comments.
Instead, there is only a permission to permanently delete **everyones** comment.
The exact naming is: `Delete Not Own and Permanent Comment Delete`.

Please fix YouTrack to let me fully delete my own comments (permanent delete) without allowing to permanent delete someone else comments.

There must be an option to permanently delete my own inputs/comments without being able to delete someone else comments.

**Comment by jk1** [comment]
@flowl thank you for getting in touch.
May I ask you to provide a reference to the GDPR article that is considered violated?

**Comment by flowl** [comment]
@jk1 I'm not a lawyer, but I know when things aren't as they should be (GDPR is user centric, not company centric).

1. When you offer a delete button which is not deleting content but just hiding it, this is giving the user a wrong assumption that data has been removed when in fact it hasn't.
2. The processes to delete information must be reasonable: I cannot send an email (which itself contains personal data) everytime I want a comment to be deleted (imagine on Facebook/Twitter/Instagram/... someone would have to email them just to remove a comment). This would ultimately aggregate more personal data than before the request (= counter user centric).

It would be sufficient if you split the permission `Delete Not Own and Permanent Comment Delete` into three seperate options and remove the fake-delete label:
1. `Hide Not Own Comment`
2. `Permanent Own Comment Delete`
3. `Permanent Not Own Comment Delete`

Then make `Permanent Own Comment Delete` permission active by default.

The fact that you are hiding comments instead of letting my delete my content is a big step backwards regarding data privacy and UX.

**Comment by jk1** [comment]
@flowl thank you for your detailed response. 

The GDPR is user-centric for sure. Yet it is focused on the personal data, not on any arbitrary piece of information a person leaves somewhere. As an example, please consider this particular GitHub page. As it's public we can safely assume that Google search engine has indexed it by now. Do we, meaning both of us, have direct means to remove this information from a search index cache? We don't. What we can do is to file a complaint to Google to forget everything crawled from here. Yet it doesn't mean Google violates the DGPR. According to Article 17.1. e GDPR, a data subject may request a search engine provider to delist one or more search results if the personal data need to be erased in compliance with a legal obligation in Union or Member State Law to which the search engine provider is subject. As you can see, not only the GDPR mentions personal data explicitly, it also does describe a similar process as reasonable.

Your suggestion to split the permission is a valid feature request per se, but it doesn't seem to have a direct connection with GDPR I'm afraid.

**Comment by flowl** [comment]
Hi @jk1 ,

I appreciate your answer, although I don't fully agree with it.
There is a difference between "doing the least to comply with law" and "following principles of the law's intention".
The intention of DSGVO/GDPR is to give the user control. I don't have control over my comments.
Search the web for the keywords "dark pattern privacy".

Also regarding your example: When I delete my content from GitHub, Google will automatically remove it from their SERP (with a delay of course).

I am working at projects where I need to use YouTrack and I cannot use the comment function until I am able to delete my own comments without calling the administrator. The administrator on their side don't want to give me permission to delete everyone else comments permanently.

Again, I appreciate your feedback but I need to wait until this has changed in the future until I can fully use YouTrack.

**Comment by flowl** [comment]
Is there an option for the administrator to click on "permanently remove all comments from user xyz" ?
Or do they have manually search up all comments and permanently delete them one after the other?

**Comment by jk1** [comment]
Hi @flowl,

A dark pattern privacy is a rather strong claim to make. It assumes that JetBrains or YouTrack team deceives you intentionally for the sake of our own benefit. I can assure you that it is not and was never the case.

I fully agree with you that the purpose of GDPR is to give you control. But yet again, a control over your personal data, not just any data. We can debate over principles of the law's intention forever, but this distinction is clearly written in the the law.

> Is there an option for the administrator to click on "permanently remove all hidden comments from user xyz" ?

There's no button to do that. What the administrator can do is to implement a workflow to get automatically notified every time you hide a comment .

> Imagine someone has 1000 comments hidden and wants to have them permanently removed without permanently deleting the whole user account.

Frankly speaking, it's hard to imagine why to hide so many comments in the first place.

**Comment by flowl** [comment]
A comment contains my name, my name is personal data, isn't it?
The comment also contains a timestamp and an indice that I probably worked on a project at the given time.
Depending on the content of the comment, there might be more information inside.

It is a kind of dark pattern. The comments do have a "Delete" button which are not deleting a comment. It's fake.
The benefit is for the company who is using YouTrack to have a shadow copy of my comment (and data) even when I "deleted" the comment. That's a dark pattern.

Please take this as a feature request into your feature request system to split the permissions so my partner's can decide on their own whether they'd like to use improved or lowered data privacy mechanics.

I am not forcing or requirig you to improve privacy, I just request giving control and choices.

Thanks for the exchange about this topic!
