### ISSUE TITLE
Fix Workflow Editor for OSX 10.10

### ISSUE THREAD

**Issue by sc0rp10** [JetBrains/youtrack-workflows#3]
When i try to run Editor (build 8452) at my macbook, I get this alert:
![](http://cdn.weblab.pro/qdHOD.png)

(you cannot open the application because it is not supported on this type of mac)
If i run `youtrack-workflow.app/youtrack-workflow.sh` in console i get this message:
![](http://cdn.weblab.pro/WUpSl.png)

But i do not want downgrade my Java version - this is default OS version.

**Comment by kradima** [comment]
Please follow https://youtrack.jetbrains.com/issue/JT-25894.

**Comment by sc0rp10** [comment]
Thank you, I bought JIRA. It just works.

**Comment by iMoses** [comment]
Yep, that an issue. The workflow editor doesn't seem to work because Java's version is too high, and I'm not about to degrade it. Also, when trying to import a workflow using the web GUI nothing happens. It isn't added, no error to success notification, nothing.
This is a deal breaker as I cannot do a simple thing such as accumulate sub-tasks estimations into their parents without using custom workflows.

Now, I don't wanna use Jira since I am already using a bunch of your products (TeamCity, IntelliJ), but it seems to me like I don't really have a choice.
Judging by this repository's issue tracker, I won't raise my hopes. It's a shame.

**Comment by mariyadavydova** [comment]
@iMoses Could you please follow the editor problem solution in https://youtrack.jetbrains.com/issue/JT-25894 ?

**Comment by rushimusmaximus** [comment]
Workflows seem powerful, but the editor is a big roadblock for me. I'm running macOS 10.12.

I was able to get the released version to launch from the command line by setting my `JDK_HOME` environment variable to the JDK 6 home and then running `./you-track-workflow.sh` however the editor seems mostly broken. Selecting text with a mouse doesn't work (can be done using keyboard with shift-arrow), downloaded workflows appear as being full of errors, auto-completion doesn't work. The worst part is that the workflows are generated code - using a standard editor even without code completion isn't an option. 

I also tried the "fixed" Mac version in the ticket above (http://download.jetbrains.com/charisma/youtrack-workflow-editor-3384fix-macos.zip). This one launches in the Finder, but functions the same.

Does the editor work properly on other platforms?
<img width="610" alt="screenshot 2017-03-30 09 51 59" src="https://cloud.githubusercontent.com/assets/4422015/24516210/b52c137a-152e-11e7-9f9a-95bf7f855c01.png">

**Comment by kradima** [comment]
It seems you didn't download custom fields schema and workflows into the Workflow editor.
Also, in-browser workflow editor is coming soon - https://blog.jetbrains.com/youtrack/2017/03/youtrack-2017-roadmap.

**Comment by rushimusmaximus** [comment]
Ah, you are right. Thanks for getting back to me and pointing this out - I'm glad it's not as 'broken' as it seemed. Definitely looking forward to the web-based editor, that sounds great!

**Comment by nafg** [comment]
Web-based editor is here (albeit experimental)

**Comment by mariyadavydova** [comment]
Just for the record:
In-browser Workflow Editor is available since 2017.3.
Standalone Workflow Editor is already deprecated. Old-fashion workflows will be deprecated quite soon as well.
