### ISSUE TITLE
How to use the 'Unblocked' State in a search?

### ISSUE THREAD

**Issue by binarykitchen** [JetBrains/youtrack-workflows#4]
https://github.com/JetBrains/youtrack-workflows/tree/master/%27Unblocked%27%20State is very nice. But how can I integrate this into a search and save it for latter use? Something like

```
for: me #Unresolved State: unblocked
```

would be great. Any clues?

**Comment by mariyadavydova** [comment]
Your search query is perfectly correct. To save this query you need to type it in the search bar on Issue List screen and then click on 'Save search' link right below the search bar. The link to this search will appear in your left pane of the issue list. You can then reuse it as is or, say, in an Issue List widget for your Dashboard.
